apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: shopsphere
data:
  POSTGRES_DB: "shopsphere"
  POSTGRES_USER: "shopsphere"

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: shopsphere
type: Opaque
stringData:
  POSTGRES_PASSWORD: "postgres-change-in-prod"
