spring:
  application:
    name: recommendation-service
  data:
    mongodb:
      uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}/${MONGO_DB:shopsphere_recommendations}
      auto-index-creation: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: recommendation-service
      auto-offset-reset: earliest

server:
  port: ${SERVER_PORT:8011}

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,info
  endpoint:
    health:
      show-details: always

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
  instance:
    hostname: ${HOSTNAME:localhost}
    prefer-ip-address: true

logging:
  level:
    root: INFO
    com.rudraksha.shopsphere: DEBUG
